from turtle import Turtle, Screen

tim = Turtle()
tim.color("White")
tim.hideturtle()
tim.speed("fastest")
tim.pensize(9)

tim.right(90)
tim.forward(160)
tim.left(50)
tim.forward(70)
tim.left(130)
tim.forward(100)
tim.penup()
tim.forward(30)
tim.pendown()
tim.right(90)
tim.forward(100)
tim.right(90)
tim.forward(130)
tim.left(135)
tim.forward(50)
tim.left(45)
tim.forward(155)
tim.penup()
tim.right(90)
tim.forward(25)
tim.right(90)
tim.forward(150)
tim.pendown()
tim.left(180)
tim.forward(170)
tim.left(45)
tim.forward(90)
tim.left(135)
tim.forward(90)
tim.penup()
tim.forward(30)
tim.right(90)
tim.pendown()
tim.forward(95)
tim.right(90)
tim.forward(110)
tim.left(110)
tim.forward(35)
tim.left(70)
tim.forward(180)
tim.penup()
tim.right(90)
tim.forward(22)
tim.right(90)
tim.pendown()
tim.forward(180)


screen = Screen()
screen.bgcolor("Black")
screen.exitonclick()
